language: objective-c
osx_image: xcode7.3
xcode_workspace: Itinerary.xcworkspace
xcode_scheme: Itinerary
before_install:
- sudo gem install cocoapods
- pod setup
- pod install
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
script:
- xctool -workspace Itinerary.xcworkspace -scheme Itinerary build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
